### ISSUE TITLE
Win32 application crashed

### ISSUE THREAD

**Issue by YumeMichi** [kotori2/Playground-SIF#14]
```
Source: Latest commit: macOS: Prevent game initialized twice
Compiler: VS 2019
Cmd: MSBuild C:\Users\Tony\Desktop\Playground-SIF-master\Engine\porting\Win32\OSSGameLibraryWin32.sln /m /verbosity:normal
SIF: JP v8.0.2 (v9.0.2 unable to load some lua)
```

Screenshot
![Imgur](https://i.imgur.com/ryGfS9R.jpg)

v9.0.2
![Imgur](https://i.imgur.com/jppzNQv.jpg)

**Comment by kotori2** [comment]
On first ss it seems there is failed C call.
On second ss there is a C function missing which seems easy to implemented.

**Comment by kotori2** [comment]
Currently stucked at 
```
SCRIPT ERROR/ runtime error: attempt to call a nil value
stack traceback: (392)
```
with 9.0.2 client.

**Comment by kotori2** [comment]
Fixed. Currently stucked at download page because missing polygon related stuffs.
