### ISSUE TITLE
NowAssetLoading doesn't disappear even if NowAssetLoading.finish() called

### ISSUE THREAD

**Issue by kotori2** [kotori2/Playground-SIF#6]
happens in mdl, gonna investigate later

**Comment by Salaron** [comment]
Also images doesn't get updated automatically, even when it downloaded successfully through microDL.

**Comment by kotori2** [comment]
SWF player is killed, but not working
![image](https://user-images.githubusercontent.com/17663689/73275602-545e2a00-4222-11ea-9a49-8279539636fa.png)

**Comment by kotori2** [comment]
Hmmmm weird, lua tries to initialize SWF player twice and release only 1 after download finished

**Comment by kotori2** [comment]
spinner fixed in b8ea2ae, reload texture callback is still not working rn

**Comment by kotori2** [comment]
Fixed in d5d2f0b3cf
